-- Database backup for playlists table - 2025-09-17T10:05:00Z
-- Generated before admin save/upload flow fixes
-- Note: Currently no playlists in the database

-- This file serves as a backup placeholder for the playlists table
-- Table structure:
-- CREATE TABLE public.playlists (
--   id uuid NOT NULL DEFAULT gen_random_uuid(),
--   title text NOT NULL,
--   description text,
--   thumbnail_url text,
--   created_by uuid,
--   created_at timestamp with time zone NOT NULL DEFAULT now(),
--   updated_at timestamp with time zone NOT NULL DEFAULT now()
-- );