// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpkcwzclgnnvrmljeyyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwa2N3emNsZ25udnJtbGpleXl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDg2MTIsImV4cCI6MjA3MjM4NDYxMn0.Mzx0RkeH08SqSjKdBotN0zOjZvw5fN3B3zba6lV5bwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});